# Generated by Django 5.0.2 on 2024-02-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_nit_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
