# Generated by Django 5.0.2 on 2024-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nit_provider',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
