# Generated by Django 5.0.2 on 2024-07-15 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customer_nit_alter_financial_nit_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nit_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='nit'),
        ),
    ]
