# Generated by Django 5.0.2 on 2024-07-18 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
