# Generated by Django 5.0.2 on 2024-07-24 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_fee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
