# Generated by Django 4.1.5 on 2023-01-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('lened', models.CharField(max_length=100, null=True)),
                ('paid', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Pagado', 'Pagado'), ('No Pagado', 'No pagado')], max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
