# Generated by Django 4.1.5 on 2023-01-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Customer',
        ),
    ]
