# Generated by Django 4.1.5 on 2023-01-29 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0002_rename_clientes_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lened',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='paid',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='category',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lened', models.CharField(max_length=100, null=True)),
                ('credit', models.CharField(max_length=100, null=True)),
                ('paid', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Pagado', 'Pagado'), ('No Pagado', 'No pagado')], max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inv.customer')),
            ],
        ),
    ]
