# Generated by Django 4.1.5 on 2023-01-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0003_rename_lened_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='category',
            new_name='status',
        ),
    ]
