# Generated by Django 4.1.5 on 2023-02-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0005_alter_customer_id_alter_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('times_paid', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inv.customer')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inv.payment')),
            ],
        ),
    ]
