# Generated by Django 4.1.5 on 2023-02-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0007_remove_quotas_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotas',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inv.customer'),
        ),
    ]
